steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/feature-${_FEATURE_ID}:${COMMIT_SHA}', '.']  
#   dir: ${_REPO_NAME}
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/${PROJECT_ID}/feature-${_FEATURE_ID}:${COMMIT_SHA}']  
# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: 'bash'
#   args: [ '-c', 'gcloud  beta secrets versions access latest --secret=${_ENV_SECRETS} > env.json' ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/bash
  env:
     - FEATURE_ID=${_FEATURE_ID}
     - COMMIT_SHA=$COMMIT_SHA
     - PROJECT_ID=$PROJECT_ID
  args:
  - '-c'
  - |
      ./cloudrun.sh
     
substitutions:
   _FEATURE_ID: abc
   _ENV_SECRETS: cloudrun-secret 
